# docker volumes are file systems Volumes are used to store data outside the container,
# so it persists even if the container is removed or recreated.
services:
  db:
    image: mysql:latest
    environment:
      # allow root user to connect from any host ('%' wildcard for all hosts)
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: twitch
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      TZ: UTC
    volumes:
      - mysql-local:/var/lib/mysql
    ports:
      # Maps port 3306 on the host machine to port 3306 in the container
      - "3307:3306"

# permanent storage of data, define a named volume called mysql-local
# did not add any feature to it
volumes:
  mysql-local: